# Site settings
title: "我的部屋"
logo: logo.png 
email: quanwei9958@126.com
description: > # this means to ignore newlines until "url:"
  吃香蕉才对嘛
url: "" # the base hostname & protocol for your site
baseurl: "/blog" # the subpath of your site, e.g. /blog/
github_username:  Qquanwei

permalink: pretty
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-paginate
